{% set version = "2.2.3" %}

package:
  name: bob.db.mnist
  version: {{ version }}

source:
  fn: bob.db.mnist-{{ version }}.zip
  md5: 1545e94944a473318f3285c713d5e5b4
  url: https://pypi.io/packages/source/b/bob.db.mnist/bob.db.mnist-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.db.base

  run:
    - python
    - bob.db.base

test:
  commands:
    - nosetests -sv bob.db.mnist

  imports:
    - bob
    - bob.db
    - bob.db.mnist

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: MNIST Database Access API for Bob

extra:
  recipe-maintainers:
    - 183amir
